QUIZ_QUESTIONS = [
    {
        "id": 1001,
        "question": "What does SELECT * do in SQL?",
        "options": ["Selects all columns", "Selects all tables", "Selects all databases", "Selects all rows only"],
        "correct_index": 0,
        "explanation": "The asterisk (*) is a wildcard that selects every column from the specified table.",
    },
    {
        "id": 1002,
        "question": "Which clause filters rows BEFORE grouping and aggregation?",
        "options": ["HAVING", "WHERE", "GROUP BY", "ORDER BY"],
        "correct_index": 1,
        "explanation": "WHERE filters individual rows before any grouping or aggregation takes place.",
    },
    {
        "id": 1003,
        "question": "What does COUNT(*) count?",
        "options": ["Non-null values in first column", "All rows including NULLs", "Unique values only", "Columns in the table"],
        "correct_index": 1,
        "explanation": "COUNT(*) counts every row in the result set, regardless of NULL values.",
    },
    {
        "id": 1004,
        "question": "Which JOIN returns only rows that have matches in BOTH tables?",
        "options": ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN"],
        "correct_index": 2,
        "explanation": "INNER JOIN returns only rows where there is a match in both joined tables.",
    },
    {
        "id": 1005,
        "question": "What does the DISTINCT keyword do?",
        "options": ["Sorts the results", "Removes duplicate rows", "Limits to 10 rows", "Groups by column"],
        "correct_index": 1,
        "explanation": "DISTINCT eliminates duplicate rows from the result set, keeping only unique combinations.",
    },
    {
        "id": 1006,
        "question": "Which keyword sorts results in descending order?",
        "options": ["ASC", "DESC", "SORT", "DOWN"],
        "correct_index": 1,
        "explanation": "DESC (descending) sorts results from highest to lowest or Z to A.",
    },
    {
        "id": 1007,
        "question": "What is the result of NULL = NULL in standard SQL?",
        "options": ["TRUE", "FALSE", "NULL / unknown", "ERROR"],
        "correct_index": 2,
        "explanation": "NULL represents an unknown value, so any comparison with NULL yields NULL (unknown), not TRUE or FALSE.",
    },
    {
        "id": 1008,
        "question": "Which aggregate function returns the smallest value?",
        "options": ["MIN", "MAX", "LEAST", "SMALL"],
        "correct_index": 0,
        "explanation": "MIN() returns the minimum (smallest) value in a set of values.",
    },
    {
        "id": 1009,
        "question": "What does the HAVING clause do?",
        "options": ["Filters individual rows", "Filters groups after aggregation", "Sorts groups", "Joins tables"],
        "correct_index": 1,
        "explanation": "HAVING filters groups after GROUP BY and aggregation, unlike WHERE which filters before.",
    },
    {
        "id": 1010,
        "question": "Which operator checks if a value matches any value in a list?",
        "options": ["LIKE", "IN", "BETWEEN", "EXISTS"],
        "correct_index": 1,
        "explanation": "IN checks whether a value matches any value in a provided list.",
    },
    {
        "id": 1011,
        "question": "What is a PRIMARY KEY?",
        "options": ["A key that encrypts data", "A constraint that uniquely identifies each row", "A foreign reference", "A sorting index"],
        "correct_index": 1,
        "explanation": "A PRIMARY KEY uniquely identifies each record in a table and enforces uniqueness and non-NULL.",
    },
    {
        "id": 1012,
        "question": "Which SQL keyword is used to add new rows to a table?",
        "options": ["CREATE", "INSERT", "ADD", "APPEND"],
        "correct_index": 1,
        "explanation": "INSERT INTO adds new rows of data to an existing table.",
    },
    {
        "id": 1013,
        "question": "What is a subquery?",
        "options": ["A query inside another query", "A query that sorts data", "A query that joins two tables", "A query that creates an index"],
        "correct_index": 0,
        "explanation": "A subquery is a query nested inside another query, often used for filtering or computing values.",
    },
    {
        "id": 1014,
        "question": "Which constraint ensures a column cannot contain NULL values?",
        "options": ["UNIQUE", "NOT NULL", "CHECK", "DEFAULT"],
        "correct_index": 1,
        "explanation": "NOT NULL ensures that every row must have a value in that column.",
    },
    {
        "id": 1015,
        "question": "What does ORDER BY 2 mean?",
        "options": ["Sort by the second column", "Limit to 2 rows", "Sort descending", "Sort by row 2"],
        "correct_index": 0,
        "explanation": "ORDER BY 2 sorts the results by the second column in the SELECT list.",
    },
    {
        "id": 1016,
        "question": "Which window function assigns unique sequential integers without gaps for ties?",
        "options": ["RANK", "ROW_NUMBER", "DENSE_RANK", "NTILE"],
        "correct_index": 2,
        "explanation": "DENSE_RANK assigns the same rank to ties and does not leave gaps in the ranking sequence.",
    },
    {
        "id": 1017,
        "question": "What does a LEFT JOIN return?",
        "options": ["Only matching rows", "All rows from the left table", "All rows from the right table", "No rows if no match"],
        "correct_index": 1,
        "explanation": "LEFT JOIN returns all rows from the left table and matched rows from the right, filling with NULL where there is no match.",
    },
    {
        "id": 1018,
        "question": "Which function calculates the average of a set of values?",
        "options": ["MEAN", "AVG", "AVERAGE", "MEDIAN"],
        "correct_index": 1,
        "explanation": "AVG() is the standard SQL aggregate function for computing the arithmetic mean.",
    },
    {
        "id": 1019,
        "question": "What does UNION do when combining two SELECT statements?",
        "options": ["Keeps all duplicates", "Removes duplicate rows", "Sorts the combined result", "Joins columns horizontally"],
        "correct_index": 1,
        "explanation": "UNION combines the results of two queries and removes duplicate rows. UNION ALL keeps duplicates.",
    },
    {
        "id": 1020,
        "question": "Which clause is used to rename a column in the output?",
        "options": ["RENAME", "AS", "ALIAS", "LABEL"],
        "correct_index": 1,
        "explanation": "The AS keyword assigns a temporary alias to a column or table in the result set.",
    },
    {
        "id": 1021,
        "question": "What is the purpose of the GROUP BY clause?",
        "options": ["Sort rows", "Group rows with same values for aggregation", "Filter rows", "Join tables"],
        "correct_index": 1,
        "explanation": "GROUP BY groups rows that have the same values in specified columns into summary rows.",
    },
    {
        "id": 1022,
        "question": "Which SQL statement modifies existing data in a table?",
        "options": ["MODIFY", "UPDATE", "ALTER", "CHANGE"],
        "correct_index": 1,
        "explanation": "UPDATE modifies existing records in a table based on a condition.",
    },
    {
        "id": 1023,
        "question": "What does the LIKE operator do?",
        "options": ["Exact match", "Pattern matching", "Range check", "List membership"],
        "correct_index": 1,
        "explanation": "LIKE is used for pattern matching with wildcards such as % (any sequence) and _ (single character).",
    },
    {
        "id": 1024,
        "question": "Which transaction command permanently saves changes?",
        "options": ["ROLLBACK", "SAVE", "COMMIT", "END"],
        "correct_index": 2,
        "explanation": "COMMIT makes all changes made during the current transaction permanent.",
    },
    {
        "id": 1025,
        "question": "What does the CASE expression provide?",
        "options": ["Looping", "Conditional logic", "Exception handling", "Type casting"],
        "correct_index": 1,
        "explanation": "CASE provides if-then-else conditional logic directly within a SQL query.",
    },
]


def get_quiz_by_id(quiz_id: int):
    for q in QUIZ_QUESTIONS:
        if q["id"] == quiz_id:
            return q
    return None
